url: https://equicl.github.io
baseurl: 

# Site settings
title: EquiCL
email: exec@equicl.org
description: "Broad Interest Group for Equity in ACL, established since 2019."


# Team names, titles and social links
people:
- name: Zeerak Talat
  pic: 1
  position: President
  social:
    - title: home
      url: https://zeerak.org/

- name: Christine de Kock
  pic: 2
  position: Secretary
  social:
    - title: home
      url: https://christinedekock.com/

- name: (Vacant)
  pic: v
  position: Accounting officer
  social:
    - title: home
      url: #

- name: Fatma Elsafoury
  pic: 3
  position: Affinity group liaison
  social:
    - title: home
      url: https://efatmae.github.io/

- name: Chi-kiu (Jackie) Lo 羅致翹
  pic: 4
  position: Technical officer
  social:
    - title: home
      url: https://chikiu-jackie-lo.org/

- name: (Vacant)
  pic: v
  position: Publicity officer
  social:
    - title: home
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: http://github.com/EquiCL

# # Postal address (add as many lines as necessary)
# address:
#   - line: 3481 Melrose Place
#   - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty